export interface SkillDefinition {
    name: string;
    aliases: string[];
    weight: number;
}

export interface SkillHit {
    name: string;
    aliases: string[];
    count: number;
}

export const SKILL_DICTIONARY: SkillDefinition[] = [
    // Frontend frameworks & libraries
    { name: "react", aliases: ["react", "reactjs", "react.js", "react native"], weight: 1 },
    { name: "nextjs", aliases: ["next.js", "nextjs", "next js"], weight: 1 },
    { name: "vue", aliases: ["vue", "vue.js", "vuejs", "nuxt"], weight: 1 },
    { name: "angular", aliases: ["angular", "angularjs", "angular 2"], weight: 1 },
    { name: "svelte", aliases: ["svelte", "sveltekit"], weight: 0.9 },
    { name: "solidjs", aliases: ["solidjs", "solid.js", "solid start"], weight: 0.8 },
    { name: "remix", aliases: ["remix", "remix.run"], weight: 0.9 },
    { name: "astro", aliases: ["astro", "astro.build"], weight: 0.8 },
    { name: "gatsby", aliases: ["gatsby", "gatsby.js"], weight: 0.8 },
    { name: "htmx", aliases: ["htmx"], weight: 0.7 },
    { name: "alpinejs", aliases: ["alpine.js", "alpinejs"], weight: 0.7 },
    { name: "jquery", aliases: ["jquery"], weight: 0.6 },
    { name: "redux", aliases: ["redux", "redux toolkit", "rtk query"], weight: 0.9 },
    { name: "zustand", aliases: ["zustand"], weight: 0.8 },
    { name: "mobx", aliases: ["mobx", "mobx state tree"], weight: 0.8 },
    { name: "react-query", aliases: ["react query", "tanstack query", "react-query"], weight: 0.9 },
    { name: "react-hook-form", aliases: ["react-hook-form", "react hook form", "react-hook-forms"], weight: 0.8 },
    { name: "framer-motion", aliases: ["framer motion", "framer-motion", "motion"], weight: 0.7 },
    { name: "tailwind", aliases: ["tailwind", "tailwindcss", "tailwind css"], weight: 1 },
    { name: "bootstrap", aliases: ["bootstrap"], weight: 0.7 },
    { name: "material-ui", aliases: ["material ui", "mui", "material-ui"], weight: 0.8 },
    { name: "chakra-ui", aliases: ["chakra ui", "chakra-ui"], weight: 0.7 },
    { name: "ant-design", aliases: ["ant design", "antd"], weight: 0.7 },
    { name: "shadcn", aliases: ["shadcn", "shadcn ui"], weight: 0.8 },
    { name: "styled-components", aliases: ["styled-components", "styled components"], weight: 0.7 },
    { name: "emotion", aliases: ["emotion", "@emotion"], weight: 0.7 },
    { name: "sass", aliases: ["sass", "scss"], weight: 0.7 },
    { name: "css", aliases: ["css", "css3"], weight: 0.9 },
    { name: "html", aliases: ["html", "html5"], weight: 0.9 },
    { name: "threejs", aliases: ["three.js", "threejs", "three js"], weight: 0.7 },
    { name: "d3", aliases: ["d3.js", "d3js", "d3"], weight: 0.7 },
    { name: "chartjs", aliases: ["chart.js", "chartjs"], weight: 0.6 },
    { name: "echarts", aliases: ["echarts"], weight: 0.6 },
    { name: "webgl", aliases: ["webgl", "opengl es"], weight: 0.7 },
    { name: "storybook", aliases: ["storybook"], weight: 0.7 },
    { name: "electron", aliases: ["electron", "electron.js"], weight: 0.7 },
    { name: "tauri", aliases: ["tauri"], weight: 0.7 },
    { name: "pwa", aliases: ["pwa", "progressive web app"], weight: 0.7 },
    { name: "microfrontend", aliases: ["microfrontend", "micro frontend", "micro-frontend"], weight: 0.6 },
    { name: "ssr", aliases: ["server side rendering", "server-side rendering", "ssr"], weight: 0.7 },
    { name: "ssg", aliases: ["static site generation", "static site generator", "ssg"], weight: 0.6 },
    { name: "a11y", aliases: ["accessibility", "a11y", "wcag", "aria"], weight: 0.7 },
    { name: "i18n", aliases: ["internationalization", "i18n", "localization"], weight: 0.6 },

    // Backend frameworks
    { name: "node", aliases: ["node", "nodejs", "node.js", "express", "nest", "nestjs", "fastify", "koa", "hapi", "adonis"], weight: 1 },
    { name: "express", aliases: ["express", "express.js", "expressjs"], weight: 0.9 },
    { name: "nestjs", aliases: ["nestjs", "nest.js", "nest"], weight: 0.9 },
    { name: "fastify", aliases: ["fastify"], weight: 0.7 },
    { name: "django", aliases: ["django"], weight: 0.9 },
    { name: "flask", aliases: ["flask"], weight: 0.8 },
    { name: "fastapi", aliases: ["fastapi", "fast api"], weight: 0.9 },
    { name: "laravel", aliases: ["laravel"], weight: 0.8 },
    { name: "rails", aliases: ["ruby on rails", "rails"], weight: 0.8 },
    { name: "spring", aliases: ["spring", "spring boot", "spring-boot", "java spring"], weight: 0.9 },
    { name: "aspnet", aliases: ["asp.net", "aspnet", ".net core", "dotnet core", "c# backend"], weight: 0.8 },
    { name: "phoenix", aliases: ["phoenix", "elixir phoenix"], weight: 0.6 },
    { name: "gin", aliases: ["gin", "gin-gonic"], weight: 0.7 },
    { name: "echo", aliases: ["echo framework", "labstack echo"], weight: 0.6 },
    { name: "trpc", aliases: ["trpc", "t rpc"], weight: 0.8 },
    { name: "graphql", aliases: ["graphql", "apollo", "apollo server", "apollo client", "graphql server"], weight: 0.9 },
    { name: "hasura", aliases: ["hasura"], weight: 0.6 },
    { name: "grpc", aliases: ["grpc", "protobuf", "protocol buffers"], weight: 0.7 },
    { name: "rest", aliases: ["rest api", "restful", "rest apis", "restful api"], weight: 0.8 },
    { name: "openapi", aliases: ["openapi", "swagger", "open api spec"], weight: 0.7 },
    { name: "microservices", aliases: ["microservices", "micro-services", "micro service architecture"], weight: 0.7 },
    { name: "serverless", aliases: ["serverless", "lambda", "aws lambda"], weight: 0.7 },
    { name: "websockets", aliases: ["websocket", "websockets", "socket.io", "ws protocol"], weight: 0.7 },
    { name: "webhooks", aliases: ["webhook", "webhooks"], weight: 0.6 },

    // Languages
    { name: "typescript", aliases: ["typescript", "ts"], weight: 1 },
    { name: "javascript", aliases: ["javascript", "js", "es6", "es2015", "ecmascript", "vanilla js", "vanilla javascript"], weight: 1 },
    { name: "python", aliases: ["python", "python3"], weight: 1 },
    { name: "golang", aliases: ["golang", "go lang", "go language"], weight: 1 },
    { name: "rust", aliases: ["rust", "rust lang"], weight: 0.9 },
    { name: "java", aliases: ["java", "jvm"], weight: 0.9 },
    { name: "kotlin", aliases: ["kotlin"], weight: 0.8 },
    { name: "swift", aliases: ["swift", "swiftui"], weight: 0.8 },
    { name: "c", aliases: ["c programming", "c language", "c99", "c11"], weight: 0.8 },
    { name: "cpp", aliases: ["c++", "cpp", "c plus plus"], weight: 0.8 },
    { name: "csharp", aliases: ["c#", "c sharp", "c-sharp"], weight: 0.8 },
    { name: "objectivec", aliases: ["objective-c", "objective c"], weight: 0.6 },
    { name: "ruby", aliases: ["ruby", "ruby lang"], weight: 0.8 },
    { name: "php", aliases: ["php", "php 8"], weight: 0.8 },
    { name: "dart", aliases: ["dart"], weight: 0.8 },
    { name: "scala", aliases: ["scala"], weight: 0.7 },
    { name: "haskell", aliases: ["haskell"], weight: 0.6 },
    { name: "elixir", aliases: ["elixir"], weight: 0.7 },
    { name: "clojure", aliases: ["clojure", "clojurescript"], weight: 0.6 },
    { name: "erlang", aliases: ["erlang"], weight: 0.6 },
    { name: "groovy", aliases: ["groovy"], weight: 0.5 },
    { name: "perl", aliases: ["perl"], weight: 0.5 },
    { name: "r", aliases: ["r programming", "r language", "rstudio"], weight: 0.6 },
    { name: "matlab", aliases: ["matlab"], weight: 0.6 },
    { name: "julia", aliases: ["julia"], weight: 0.5 },
    { name: "zig", aliases: ["zig"], weight: 0.6 },
    { name: "lua", aliases: ["lua"], weight: 0.5 },
    { name: "bash", aliases: ["bash", "shell scripting", "shell script"], weight: 0.8 },
    { name: "powershell", aliases: ["powershell"], weight: 0.6 },
    { name: "sql", aliases: ["sql", "sql queries", "pl/sql", "t-sql"], weight: 1 },

    // Databases & data
    { name: "postgresql", aliases: ["postgres", "postgresql", "pgsql"], weight: 1 },
    { name: "mysql", aliases: ["mysql"], weight: 0.9 },
    { name: "sqlite", aliases: ["sqlite", "sqlite3"], weight: 0.7 },
    { name: "mssql", aliases: ["microsoft sql server", "sql server", "mssql"], weight: 0.7 },
    { name: "oracle", aliases: ["oracle database", "oracle db"], weight: 0.6 },
    { name: "mongodb", aliases: ["mongodb", "mongo", "mongo db"], weight: 0.9 },
    { name: "redis", aliases: ["redis", "redis cache"], weight: 0.9 },
    { name: "memcached", aliases: ["memcached"], weight: 0.5 },
    { name: "elasticsearch", aliases: ["elasticsearch", "elastic search"], weight: 0.7 },
    { name: "kibana", aliases: ["kibana"], weight: 0.6 },
    { name: "cassandra", aliases: ["cassandra", "apache cassandra"], weight: 0.6 },
    { name: "dynamodb", aliases: ["dynamodb", "dynamo db", "aws dynamodb"], weight: 0.7 },
    { name: "couchbase", aliases: ["couchbase"], weight: 0.5 },
    { name: "neo4j", aliases: ["neo4j"], weight: 0.6 },
    { name: "clickhouse", aliases: ["clickhouse"], weight: 0.6 },
    { name: "cockroachdb", aliases: ["cockroachdb", "cockroach db"], weight: 0.5 },
    { name: "firebase", aliases: ["firebase", "firestore", "firebase cloud"], weight: 0.8 },
    { name: "supabase", aliases: ["supabase"], weight: 0.8 },
    { name: "prisma", aliases: ["prisma", "prisma orm"], weight: 0.9 },
    { name: "typeorm", aliases: ["typeorm", "type orm"], weight: 0.7 },
    { name: "drizzle", aliases: ["drizzle orm", "drizzle"], weight: 0.7 },
    { name: "sequelize", aliases: ["sequelize"], weight: 0.7 },
    { name: "mongoose", aliases: ["mongoose"], weight: 0.7 },
    { name: "knex", aliases: ["knex"], weight: 0.6 },
    { name: "sqlalchemy", aliases: ["sqlalchemy", "sql alchemy"], weight: 0.7 },
    { name: "bigquery", aliases: ["bigquery", "big query"], weight: 0.7 },
    { name: "snowflake", aliases: ["snowflake"], weight: 0.7 },
    { name: "spark", aliases: ["apache spark", "spark"], weight: 0.7 },
    { name: "hadoop", aliases: ["hadoop"], weight: 0.6 },
    { name: "kafka", aliases: ["kafka", "apache kafka"], weight: 0.7 },
    { name: "rabbitmq", aliases: ["rabbitmq", "rabbit mq"], weight: 0.7 },
    { name: "kinesis", aliases: ["kinesis", "aws kinesis"], weight: 0.6 },
    { name: "sqs", aliases: ["sqs", "aws sqs"], weight: 0.6 },
    { name: "etl", aliases: ["etl", "extract transform load", "data pipeline", "data pipelines"], weight: 0.7 },
    { name: "dbt", aliases: ["dbt", "data build tool"], weight: 0.6 },
    { name: "airbyte", aliases: ["airbyte"], weight: 0.5 },

    // DevOps & cloud
    { name: "docker", aliases: ["docker", "docker compose", "docker-compose", "containers", "containerization"], weight: 1 },
    { name: "kubernetes", aliases: ["kubernetes", "k8s", "kube"], weight: 0.9 },
    { name: "helm", aliases: ["helm"], weight: 0.7 },
    { name: "istio", aliases: ["istio"], weight: 0.6 },
    { name: "terraform", aliases: ["terraform", "iac", "infrastructure as code"], weight: 0.8 },
    { name: "ansible", aliases: ["ansible"], weight: 0.7 },
    { name: "puppet", aliases: ["puppet"], weight: 0.5 },
    { name: "chef", aliases: ["chef"], weight: 0.5 },
    { name: "cloudformation", aliases: ["cloudformation", "aws cloudformation"], weight: 0.6 },
    { name: "pulumi", aliases: ["pulumi"], weight: 0.6 },
    { name: "aws", aliases: ["aws", "amazon web services", "ec2", "s3", "rds", "ecs", "eks", "cloudwatch", "iam"], weight: 1 },
    { name: "azure", aliases: ["azure", "microsoft azure", "azure devops", "azure functions"], weight: 0.9 },
    { name: "gcp", aliases: ["gcp", "google cloud", "google cloud platform"], weight: 0.9 },
    { name: "cloudflare", aliases: ["cloudflare", "cloudflare workers"], weight: 0.7 },
    { name: "vercel", aliases: ["vercel"], weight: 0.7 },
    { name: "netlify", aliases: ["netlify"], weight: 0.6 },
    { name: "heroku", aliases: ["heroku"], weight: 0.5 },
    { name: "nginx", aliases: ["nginx"], weight: 0.7 },
    { name: "apache", aliases: ["apache http server", "apache server"], weight: 0.6 },
    { name: "caddy", aliases: ["caddy"], weight: 0.5 },
    { name: "linux", aliases: ["linux", "ubuntu", "centos", "debian", "unix"], weight: 0.8 },
    { name: "ci-cd", aliases: ["ci/cd", "continuous integration", "continuous deployment", "continuous delivery", "cicd"], weight: 0.8 },
    { name: "github-actions", aliases: ["github actions", "github-actions", "gh actions"], weight: 0.8 },
    { name: "gitlab-ci", aliases: ["gitlab ci", "gitlab-ci"], weight: 0.7 },
    { name: "jenkins", aliases: ["jenkins"], weight: 0.7 },
    { name: "circleci", aliases: ["circleci", "circle ci"], weight: 0.6 },
    { name: "travis", aliases: ["travis ci", "travis-ci"], weight: 0.5 },
    { name: "argo", aliases: ["argo cd", "argocd", "argo workflows"], weight: 0.6 },
    { name: "prometheus", aliases: ["prometheus"], weight: 0.7 },
    { name: "grafana", aliases: ["grafana"], weight: 0.7 },
    { name: "loki", aliases: ["loki"], weight: 0.5 },
    { name: "datadog", aliases: ["datadog"], weight: 0.6 },
    { name: "newrelic", aliases: ["new relic", "newrelic"], weight: 0.5 },
    { name: "sentry", aliases: ["sentry", "sentry.io"], weight: 0.6 },
    { name: "vault", aliases: ["hashicorp vault", "vault"], weight: 0.6 },
    { name: "consul", aliases: ["consul"], weight: 0.5 },
    { name: "jaeger", aliases: ["jaeger"], weight: 0.5 },
    { name: "opentelemetry", aliases: ["opentelemetry", "open telemetry", "otel"], weight: 0.6 },
    { name: "observability", aliases: ["observability", "monitoring", "logging", "tracing"], weight: 0.6 },
    { name: "sre", aliases: ["sre", "site reliability"], weight: 0.6 },
    { name: "s3", aliases: ["s3", "amazon s3", "aws s3"], weight: 0.7 },
    { name: "dns", aliases: ["dns", "domain name system"], weight: 0.5 },
    { name: "load-balancing", aliases: ["load balancer", "load balancing", "lb"], weight: 0.5 },

    // Mobile
    { name: "react-native", aliases: ["react native", "react-native", "rn"], weight: 0.9 },
    { name: "expo", aliases: ["expo"], weight: 0.7 },
    { name: "flutter", aliases: ["flutter"], weight: 0.9 },
    { name: "android", aliases: ["android", "android sdk"], weight: 0.8 },
    { name: "ios", aliases: ["ios", "ios development"], weight: 0.8 },
    { name: "swiftui", aliases: ["swiftui", "swift ui"], weight: 0.7 },
    { name: "uikit", aliases: ["uikit"], weight: 0.6 },
    { name: "ionic", aliases: ["ionic"], weight: 0.6 },
    { name: "capacitor", aliases: ["capacitor"], weight: 0.6 },
    { name: "unity", aliases: ["unity", "unity3d"], weight: 0.7 },
    { name: "xamarin", aliases: ["xamarin"], weight: 0.5 },

    // AI / ML / Data science
    { name: "machine-learning", aliases: ["machine learning", "ml", "ml models"], weight: 1 },
    { name: "deep-learning", aliases: ["deep learning", "deep neural networks"], weight: 0.9 },
    { name: "tensorflow", aliases: ["tensorflow", "tf"], weight: 0.8 },
    { name: "pytorch", aliases: ["pytorch", "torch"], weight: 0.9 },
    { name: "keras", aliases: ["keras"], weight: 0.6 },
    { name: "scikit-learn", aliases: ["scikit-learn", "sklearn", "scikit learn"], weight: 0.7 },
    { name: "pandas", aliases: ["pandas"], weight: 0.7 },
    { name: "numpy", aliases: ["numpy"], weight: 0.7 },
    { name: "opencv", aliases: ["opencv", "open cv"], weight: 0.6 },
    { name: "nlp", aliases: ["nlp", "natural language processing"], weight: 0.8 },
    { name: "llm", aliases: ["llm", "large language model", "large language models", "gpt", "claude", "gemini"], weight: 0.9 },
    { name: "langchain", aliases: ["langchain", "lang chain"], weight: 0.8 },
    { name: "llama-index", aliases: ["llamaindex", "llama index", "llama-index"], weight: 0.6 },
    { name: "openai", aliases: ["openai", "open ai"], weight: 0.7 },
    { name: "huggingface", aliases: ["hugging face", "huggingface", "transformers"], weight: 0.7 },
    { name: "rag", aliases: ["rag", "retrieval augmented generation"], weight: 0.7 },
    { name: "agents", aliases: ["ai agents", "agentic", "autonomous agents"], weight: 0.6 },
    { name: "computer-vision", aliases: ["computer vision", "image recognition", "object detection"], weight: 0.7 },
    { name: "reinforcement-learning", aliases: ["reinforcement learning"], weight: 0.6 },
    { name: "mlops", aliases: ["mlops", "ml ops", "model deployment"], weight: 0.7 },
    { name: "onnx", aliases: ["onnx"], weight: 0.5 },
    { name: "vector-db", aliases: ["vector database", "vector databases", "vector db", "pinecone", "weaviate", "qdrant", "chroma", "milvus"], weight: 0.7 },

    // Testing
    { name: "jest", aliases: ["jest"], weight: 0.8 },
    { name: "vitest", aliases: ["vitest"], weight: 0.8 },
    { name: "mocha", aliases: ["mocha"], weight: 0.6 },
    { name: "chai", aliases: ["chai"], weight: 0.6 },
    { name: "jasmine", aliases: ["jasmine"], weight: 0.5 },
    { name: "cypress", aliases: ["cypress"], weight: 0.7 },
    { name: "playwright", aliases: ["playwright"], weight: 0.8 },
    { name: "selenium", aliases: ["selenium"], weight: 0.7 },
    { name: "puppeteer", aliases: ["puppeteer"], weight: 0.6 },
    { name: "testing-library", aliases: ["testing library", "react testing library", "rtl"], weight: 0.7 },
    { name: "pytest", aliases: ["pytest"], weight: 0.7 },
    { name: "junit", aliases: ["junit"], weight: 0.6 },
    { name: "phpunit", aliases: ["phpunit"], weight: 0.6 },
    { name: "rspec", aliases: ["rspec"], weight: 0.6 },
    { name: "unit-testing", aliases: ["unit test", "unit testing", "unit tests"], weight: 0.7 },
    { name: "e2e", aliases: ["e2e", "end to end testing", "end-to-end testing"], weight: 0.7 },
    { name: "tdd", aliases: ["tdd", "test driven development"], weight: 0.6 },
    { name: "postman", aliases: ["postman"], weight: 0.6 },
    { name: "k6", aliases: ["k6"], weight: 0.5 },
    { name: "jmeter", aliases: ["jmeter"], weight: 0.5 },

    // Tools & platforms
    { name: "git", aliases: ["git", "version control"], weight: 0.9 },
    { name: "github", aliases: ["github", "github api", "github actions"], weight: 0.8 },
    { name: "gitlab", aliases: ["gitlab"], weight: 0.7 },
    { name: "bitbucket", aliases: ["bitbucket"], weight: 0.5 },
    { name: "jira", aliases: ["jira"], weight: 0.6 },
    { name: "npm", aliases: ["npm", "npm registry"], weight: 0.7 },
    { name: "yarn", aliases: ["yarn"], weight: 0.6 },
    { name: "pnpm", aliases: ["pnpm"], weight: 0.6 },
    { name: "bun", aliases: ["bun"], weight: 0.7 },
    { name: "deno", aliases: ["deno"], weight: 0.6 },
    { name: "vite", aliases: ["vite"], weight: 0.8 },
    { name: "webpack", aliases: ["webpack"], weight: 0.7 },
    { name: "rollup", aliases: ["rollup"], weight: 0.6 },
    { name: "esbuild", aliases: ["esbuild"], weight: 0.6 },
    { name: "swc", aliases: ["swc"], weight: 0.6 },
    { name: "babel", aliases: ["babel"], weight: 0.6 },
    { name: "turborepo", aliases: ["turborepo", "turbo repo"], weight: 0.7 },
    { name: "monorepo", aliases: ["monorepo", "mono repo"], weight: 0.6 },
    { name: "nx", aliases: ["nx", "nrwl"], weight: 0.6 },
    { name: "lerna", aliases: ["lerna"], weight: 0.5 },
    { name: "figma", aliases: ["figma"], weight: 0.6 },
    { name: "oauth", aliases: ["oauth", "oauth2", "oauth 2"], weight: 0.7 },
    { name: "jwt", aliases: ["jwt", "json web token", "json web tokens"], weight: 0.7 },
    { name: "sso", aliases: ["sso", "single sign on", "oidc", "openid connect", "saml"], weight: 0.6 },
    { name: "auth", aliases: ["authentication", "authorization", "auth", "rbac", "2fa", "mfa"], weight: 0.7 },
    { name: "seo", aliases: ["seo", "search engine optimization"], weight: 0.6 },
    { name: "ffmpeg", aliases: ["ffmpeg"], weight: 0.5 },
    { name: "blender", aliases: ["blender"], weight: 0.5 },
    { name: "agile", aliases: ["agile", "scrum", "kanban", "sprint"], weight: 0.5 },
];

function escapeRegex(input: string): string {
    return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function matchText(text: string): SkillHit[] {
    const lower = text.toLowerCase();

    const hits: SkillHit[] = [];

    for (const skill of SKILL_DICTIONARY) {
        let count = 0;
        for (const alias of skill.aliases) {
            const re = new RegExp(`\\b${escapeRegex(alias)}\\b`, "g");
            count += (lower.match(re) ?? []).length;
        }
        if (count > 0) {
            hits.push({ name: skill.name, aliases: skill.aliases, count });
        }
    }

    return hits.sort((a, b) => b.count - a.count);
}

export function getSkillDictionary(): SkillDefinition[] {
    return SKILL_DICTIONARY;
}
